[package]
name = "decoder"
version = "1.5.0"
edition = "2024"
rust-version = "1.85"
description = "Decoder for ActiveAnticheatCrypt"

[[bin]]
name = "decoder"
path = "src/main.rs"

[dependencies]
obfstr = "0.4.6"
num-bigint = "0.4"
rayon = "1.10"
thiserror = "2.0"
walkdir = "2.5"
camino = "1.1"
sha1 = "0.10"

[dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Console",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Environment",
    "Win32_System_IO",
    "Win32_System_JobObjects",
    "Win32_System_Pipes",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_UI_WindowsAndMessaging",
]

[profile.release]
debug = 0
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
doc_markdown = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
too_many_lines = "allow"
borrow_as_ptr = "allow"
map_unwrap_or = "allow"
redundant_closure_for_method_calls = "allow"
implicit_clone = "allow"
format_collect = "allow"
semicolon_if_nothing_returned = "allow"
unwrap_used = "deny"
