; Pick a name the client actually loads and that you are not already using for
; something else.
; Windows 10/11:
;   ddraw.dll
;   xinput1_4.dll
;   WindowsCodecs.dll
;   RESAMPLEDMO.dll
; Windows 7:
;   xinput1_3.dll
proxy_name = ddraw.dll
scryde_gamekitdata_auto_decode = true
