//! One binary stands in for ddraw, d3d9 or xinput1_4.
//! Pre-built export table (ForwardN/OrdinalN/SharedN stubs + /EXPORT
//! aliases, stub space reused per DLL as Forward{ordinal - base}) lets the
//! loader accept any of the three names. Tables are dumpbin snapshots of the
//! 32-bit originals; distinct stub immediates defeat /OPT:ICF folding.

use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

const NAMED_SLOTS: u16 = 23;
const MAX_ORDINAL: u16 = 109;

// The same three names live in proxy.rs SHARED; change both.
const SHARED: &[&str] = &["DllCanUnloadNow", "DllGetClassObject", "SetAppCompatStringPointer"];

const DDRAW_BASE: u16 = 1;

const DDRAW: &[(&str, u16)] = &[
    ("AcquireDDThreadLock", 1),
    ("CompleteCreateSysmemSurface", 2),
    ("D3DParseUnknownCommand", 3),
    ("DDGetAttachedSurfaceLcl", 4),
    ("DDInternalLock", 5),
    ("DDInternalUnlock", 6),
    ("DSoundHelp", 7),
    ("DirectDrawCreate", 8),
    ("DirectDrawCreateClipper", 9),
    ("DirectDrawCreateEx", 10),
    ("DirectDrawEnumerateA", 11),
    ("DirectDrawEnumerateExA", 12),
    ("DirectDrawEnumerateExW", 13),
    ("DirectDrawEnumerateW", 14),
    ("DllCanUnloadNow", 15),
    ("DllGetClassObject", 16),
    ("GetDDSurfaceLocal", 17),
    ("GetOLEThunkData", 18),
    ("GetSurfaceFromDC", 19),
    ("RegisterSpecialCase", 20),
    ("ReleaseDDThreadLock", 21),
    ("SetAppCompatData", 22),
];

const XINPUT_BASE: u16 = 1;
const XINPUT: &[(&str, u16)] = &[
    ("DllMain", 1),
    ("XInputGetState", 2),
    ("XInputSetState", 3),
    ("XInputGetCapabilities", 4),
    ("XInputEnable", 5),
    ("XInputGetBatteryInformation", 7),
    ("XInputGetKeystroke", 8),
    ("XInputGetAudioDeviceIds", 10),
];

const D3D9_BASE: u16 = 16;
const D3D9: &[(&str, u16)] = &[
    ("Direct3DCreate9On12", 20),
    ("Direct3DCreate9On12Ex", 21),
    ("Direct3DShaderValidatorCreate9", 24),
    ("PSGPError", 25),
    ("PSGPSampleTexture", 26),
    ("D3DPERF_BeginEvent", 27),
    ("D3DPERF_EndEvent", 28),
    ("D3DPERF_GetStatus", 29),
    ("D3DPERF_QueryRepeatFrame", 30),
    ("D3DPERF_SetMarker", 31),
    ("D3DPERF_SetOptions", 32),
    ("D3DPERF_SetRegion", 33),
    ("DebugSetLevel", 34),
    ("DebugSetMute", 35),
    ("Direct3D9EnableMaximizedWindowedModeShim", 36),
    ("Direct3DCreate9", 37),
    ("Direct3DCreate9Ex", 38),
];

fn shared_slot(name: &str) -> Option<usize> {
    SHARED.iter().position(|shared| *shared == name)
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    // The DLL product with its /EXPORT overlay is x86-only;
    // other targets still get compiling stubs.
    if env::var("CARGO_CFG_TARGET_ARCH").as_deref() == Ok("x86") {
        emit_exports();
    } else {
        println!("cargo:warning=aa_proxy exports support x86 only");
    }
    render_stubs();
}

/// Alias every supported name onto its stub via linker /EXPORT.
/// x86 stdcall symbols are decorated as _Name@0.
fn emit_exports() {
    let decorated_name = |stub: &str| format!("_{stub}@0");

    let targets: &[(&[(&str, u16)], u16)] =
        &[(DDRAW, DDRAW_BASE), (XINPUT, XINPUT_BASE), (D3D9, D3D9_BASE)];
    for (table, base) in targets {
        for (name, ordinal) in *table {
            assert!(
                *ordinal >= *base && *ordinal <= MAX_ORDINAL,
                "ordinal out of range for {name}"
            );
            if shared_slot(name).is_none() {
                assert!(ordinal - base < NAMED_SLOTS, "slot out of range for {name}");
            }
        }
    }
    let mut seen = BTreeSet::new();
    let mut emit_export = |arg: String| {
        if seen.insert(arg.clone()) {
            println!("cargo:rustc-link-arg=/EXPORT:{arg}");
        }
    };
    for (table, base) in targets {
        for (name, ordinal) in *table {
            match shared_slot(name) {
                Some(index) => {
                    emit_export(format!(
                        "{name}={}",
                        decorated_name(&format!("ForwardShared{index}"))
                    ));
                }
                None => {
                    emit_export(format!(
                        "{name}={}",
                        decorated_name(&format!("Forward{}", ordinal - base))
                    ));
                }
            }
        }
    }
    for ordinal in 1..=MAX_ORDINAL {
        emit_export(format!(
            "{ordinal}={0},@{ordinal},NONAME",
            decorated_name(&format!("ForwardOrdinal{ordinal}"))
        ));
    }
}

fn render_stubs() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is always set by cargo"));
    let mut stubs = String::from(
        "// Generated by build.rs — do not edit.\n\
         // One patchable stub per forward slot (see build.rs header).\n",
    );
    for slot in 0..NAMED_SLOTS {
        let _ = write!(
            stubs,
            "#[allow(clippy::missing_safety_doc)]\n\
             #[unsafe(no_mangle)]\n\
             pub unsafe extern \"system\" fn Forward{slot}() {{\n\
             \x20   core::hint::black_box({slot}u32);\n\
             }}\n"
        );
    }
    for ordinal in 1..=MAX_ORDINAL {
        let _ = write!(
            stubs,
            "#[allow(clippy::missing_safety_doc)]\n\
             #[unsafe(no_mangle)]\n\
             pub unsafe extern \"system\" fn ForwardOrdinal{ordinal}() {{\n\
             \x20   core::hint::black_box({}u32);\n\
             }}\n",
            10_000 + u32::from(ordinal)
        );
    }
    for (index, _) in SHARED.iter().enumerate() {
        let _ = write!(
            stubs,
            "#[allow(clippy::missing_safety_doc)]\n\
             #[unsafe(no_mangle)]\n\
             pub unsafe extern \"system\" fn ForwardShared{index}() {{\n\
             \x20   core::hint::black_box({}u32);\n\
             }}\n",
            20_000 + index as u32
        );
    }

    let names: Vec<String> = (0..NAMED_SLOTS).map(|slot| format!("Forward{slot}")).collect();
    let _ = writeln!(
        stubs,
        "pub static FORWARD_TABLE: [unsafe extern \"system\" fn(); {NAMED_SLOTS}] = [{}];",
        names.join(", ")
    );
    let ordinals: Vec<String> =
        (1..=MAX_ORDINAL).map(|ordinal| format!("ForwardOrdinal{ordinal}")).collect();
    let _ = writeln!(
        stubs,
        "pub static FORWARD_ORDINAL_TABLE: [unsafe extern \"system\" fn(); {MAX_ORDINAL}] = [{}];",
        ordinals.join(", ")
    );
    let shared: Vec<String> =
        (0..SHARED.len()).map(|index| format!("ForwardShared{index}")).collect();
    let _ = writeln!(
        stubs,
        "pub static FORWARD_SHARED_TABLE: [unsafe extern \"system\" fn(); {}] = [{}];",
        SHARED.len(),
        shared.join(", ")
    );
    fs::write(out_dir.join("stubs.rs"), stubs).expect("cannot write the generated stubs");
}
