[package]
name = "aa_proxy"
version = "1.0.0"
edition = "2024"
description = "Universal proxy DLL. Forwards every export to the real system DLL and captures the live ActiveAnticheatCrypt RSA key"
license = "MIT"

[lib]
name = "aa_proxy"
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Environment",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
]

[lints]
workspace = true
